# Generate HTML tag environment
# 
# Generates the environment used for the HTML utility functions. Included
# as means of documentation for where the HTML utility functions come from.
.html <- new.env()
.html_tags <- scan( what=character(), sep="\n", strip.white=TRUE, quiet=TRUE,
                   text="<a>
                   <abbr>
                   <acronym>
                   <address>
                   <applet>
                   <area>
                   <b>
                   <base>
                   <basefont>
                   <bdo>
                   <big>
                   <blockquote>
                   <body>
                   <br>
                   <button>
                   <caption>
                   <center>
                   <cite>
                   <code>
                   <col>
                   <colgroup>
                   <dd>
                   <del>
                   <dfn>
                   <dir>
                   <div>
                   <dl>
                   <dt>
                   <em>
                   <fieldset>
                   <font>
                   <form>
                   <frame>
                   <frameset>
                   <h1>
                   <h2>
                   <h3>
                   <h4>
                   <h5>
                   <h6>
                   <head>
                   <hr>
                   <html>
                   <i>
                   <iframe>
                   <img>
                   <input>
                   <ins>
                   <isindex>
                   <kbd>
                   <label>
                   <legend>
                   <li>
                   <link>
                   <map>
                   <menu>
                   <meta>
                   <noframes>
                   <noscript>
                   <object>
                   <ol>
                   <optgroup>
                   <option>
                   <p>
                   <param>
                   <pre>
                   <q>
                   <s>
                   <samp>
                   <script>
                   <select>
                   <small>
                   <span>
                   <strike>
                   <strong>
                   <style>
                   <sub>
                   <sup>
                   <table>
                   <tbody>
                   <td>
                   <textarea>
                   <tfoot>
                   <th>
                   <thead>
                   <title>
                   <tr>
                   <tt>
                   <u>
                   <ul>
                   <var>
                   <article>
                   <aside>
                   <audio>
                   <bdi>
                   <canvas>
                   <command>
                   <datalist>
                   <details>
                   <embed>
                   <figcaption>
                   <figure>
                   <footer>
                   <header>
                   <hgroup>
                   <keygen>
                   <mark>
                   <meter>
                   <nav>
                   <output>
                   <progress>
                   <rp>
                   <rt>
                   <ruby>
                   <section>
                   <summary>
                   <time>
                   <track>
                   <video>
                   <wbr>")
.tags <- sort( gsub( "(<)(.*?)(>)", "\\2", .html_tags, perl=TRUE ) )
for( tag in .tags ) {
  assign( tag, makeHTMLTag(tag), envir=.html )
}

rm(.tags)
rm(.html_tags)