# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_rows_from_file_to_file <- function(input_file_name, output_file_name, delim, items_to_keep, column_to_check) {
    invisible(.Call('Kmisc_extract_rows_from_file_to_file', PACKAGE = 'Kmisc', input_file_name, output_file_name, delim, items_to_keep, column_to_check))
}

extract_rows_from_file <- function(input_file_name, delim, items_to_keep, column_to_check) {
    .Call('Kmisc_extract_rows_from_file', PACKAGE = 'Kmisc', input_file_name, delim, items_to_keep, column_to_check)
}

fast_factor <- function(x) {
    .Call('Kmisc_fast_factor', PACKAGE = 'Kmisc', x)
}

split_file <- function(path, dir, basename, path_sep, sep, prepend, file_ext, column, skip, verbose) {
    invisible(.Call('Kmisc_split_file', PACKAGE = 'Kmisc', path, dir, basename, path_sep, sep, prepend, file_ext, column, skip, verbose))
}

split_runs_numeric <- function(X) {
    .Call('Kmisc_split_runs_numeric', PACKAGE = 'Kmisc', X)
}

split_runs_character <- function(X) {
    .Call('Kmisc_split_runs_character', PACKAGE = 'Kmisc', X)
}

split_runs_one <- function(x) {
    .Call('Kmisc_split_runs_one', PACKAGE = 'Kmisc', x)
}

stack_list_df <- function(X, classes, num_elem, make_row_names, name, keep_list_index, index_name) {
    .Call('Kmisc_stack_list_df', PACKAGE = 'Kmisc', X, classes, num_elem, make_row_names, name, keep_list_index, index_name)
}

swap <- function(vec, from, to) {
    .Call('Kmisc_swap', PACKAGE = 'Kmisc', vec, from, to)
}

